# Generated by Django 5.0 on 2026-05-28 15:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0002_alter_place_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (10, "Book Presentation"),
                            (20, "Author Meeting"),
                            (30, "Discussion"),
                            (40, "Lecture"),
                            (50, "Book Club"),
                            (60, "Other"),
                        ],
                        default=60,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="places.place",
                    ),
                ),
            ],
        ),
    ]
