# Generated by Django 5.0 on 2026-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.DateTimeField(),
        ),
    ]
