# Generated by Django 5.0 on 2026-09-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_options_alter_event_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="description_pl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_pl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
