# Generated by Django 5.0 on 2026-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='categories',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.IntegerField(choices=[(10, 'Library'), (20, 'Bookshop'), (30, 'Cultural Centre'), (40, 'Café'), (50, 'Museum'), (60, 'Other')], default=60),
        ),
    ]
