# Generated by Django 5.0 on 2026-05-28 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["-created_at"]},
        ),
    ]
