# Generated by Django 5.0 on 2026-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_place_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="place",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
