# Generated by Django 5.0 on 2026-09-01 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
